services:
    netgen.ezplatform_site.event_listener.view_tagger:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\EventListener\ViewTaggerSubscriber
        arguments:
            - '@ezplatform.view_cache.response_tagger.dispatcher'
        tags:
            - { name: kernel.event_subscriber }

    netgen.ezplatform_site.event_listener.invalid_redirect_configuration:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\EventListener\InvalidRedirectConfigurationListener
        public: false
        arguments:
            - '@router'
            - '@ezpublish.config.resolver'
            - '@?logger'
        tags:
            - { name: kernel.event_subscriber }
