services:
    netgen.ezplatform_site.twig.extension.field_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\FieldRenderingExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen.ezplatform_site.twig.runtime.field_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\FieldRenderingRuntime
        # public: false
        arguments:
            - '@twig'
            - '@ezpublish.templating.field_block_renderer'
            - '@ezpublish.fieldType.parameterProviderRegistry'
        tags:
            - { name: twig.runtime }

    netgen.ezplatform_site.twig.extension.content_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\ContentViewExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen.ezplatform_site.twig.runtime.content_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\ContentViewRuntime
        # public: false
        arguments:
            - '@netgen.ezplatform_site.view_builder.content'
            - '@netgen.ezplatform_site.view_renderer'
        tags:
            - { name: twig.runtime }

    netgen.ezplatform_site.twig.extension.embedded_content_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\EmbeddedContentViewExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen.ezplatform_site.twig.runtime.embedded_content_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\EmbeddedContentViewRuntime
        # public: false
        arguments:
            - '@netgen.ezplatform_site.view_builder.content'
            - '@netgen.ezplatform_site.view_renderer'
        tags:
            - { name: twig.runtime }

    netgen.ezplatform_site.twig.extension.ez_content_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\EzContentViewExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen.ezplatform_site.twig.runtime.ez_content_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\EzContentViewRuntime
        # public: false
        arguments:
            - '@ezpublish.view_builder.content'
            - '@netgen.ezplatform_site.view_renderer'
        tags:
            - { name: twig.runtime }

    netgen.ezplatform_site.twig.extension.ez_embedded_content_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\EzEmbeddedContentViewExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen.ezplatform_site.twig.runtime.ez_embedded_content_rendering:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\EzEmbeddedContentViewRuntime
        # public: false
        arguments:
            - '@ezpublish.view_builder.content'
            - '@netgen.ezplatform_site.view_renderer'
        tags:
            - { name: twig.runtime }

    netgen.ezplatform_site.twig.extension.image:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\ImageExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen.ezplatform_site.twig.runtime.image:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\ImageRuntime
        # public: false
        arguments:
            - '@ezpublish.fieldType.ezimage.variation_service'
            - '@?logger'
        tags:
            - { name: twig.runtime }

    netgen.ezplatform_site.twig.extension.query:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\QueryExtension
        tags:
            - { name: twig.extension }
        public: false

    netgen.ezplatform_site.twig.runtime.query:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\QueryRuntime
        # public: false
        arguments:
            - '@netgen.ezplatform_site.query_type.query_executor'
        tags:
            - { name: twig.runtime }

    netgen.ezplatform_site.twig.extension.get_attr_expression:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\GetAttrExpressionExtension
        tags:
            - { name: twig.extension }
        public: false

    netgen.ezplatform_site.twig.extension.named_object:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\NamedObjectExtension
        tags:
            - { name: twig.extension }
        public: false

    netgen.ezplatform_site.twig.runtime.named_object:
        class: Netgen\Bundle\EzPlatformSiteApiBundle\Templating\Twig\Extension\NamedObjectRuntime
        # public: false
        arguments:
            - '@netgen.ezplatform_site.named_object_provider'
            - '%kernel.debug%'
            - '@?logger'
        tags:
            - { name: twig.runtime }
            - { name: monolog.logger, channel: ngsiteapi }
