parameters:
    # Default view templates
    netgen.ezplatform_site.default_view_templates.content.asset_image: "@@NetgenEzPlatformSiteApi/default/content/asset_image.html.twig"
    netgen.ezplatform_site.default_view_templates.content.embed: "@@NetgenEzPlatformSiteApi/default/content/embed.html.twig"
    netgen.ezplatform_site.default_view_templates.content.embed_image: "@@NetgenEzPlatformSiteApi/default/content/embed_image.html.twig"
    netgen.ezplatform_site.default_view_templates.content.embed_inline: "@@NetgenEzPlatformSiteApi/default/content/embed_inline.html.twig"
    netgen.ezplatform_site.default_view_templates.content.full: "@@NetgenEzPlatformSiteApi/default/content/full.html.twig"
    netgen.ezplatform_site.default_view_templates.content.line: "@@NetgenEzPlatformSiteApi/default/content/line.html.twig"
    netgen.ezplatform_site.default_view_templates.content.text_linked: "@@NetgenEzPlatformSiteApi/default/content/text_linked.html.twig"
    # List of content type identifiers to display as image when embedded
    netgen.ezplatform_site.content_view.image_embed_content_type_identifiers: ['image']

    # Default eZ Platform settings
    # By default we don't override URL alias view action, for that reason this is commented out
    #ezsettings.default.pagelayout: '@@NetgenEzPlatformSiteApi/pagelayout.html.twig'

    ezsettings.default.ng_fieldtypes.ezrichtext.embed.content:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/content.html.twig"
    ezsettings.default.ng_fieldtypes.ezrichtext.embed.content_denied:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/content_denied.html.twig"
    ezsettings.default.ng_fieldtypes.ezrichtext.embed.content_inline:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/content_inline.html.twig"
    ezsettings.default.ng_fieldtypes.ezrichtext.embed.content_inline_denied:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/content_inline_denied.html.twig"
    ezsettings.default.ng_fieldtypes.ezrichtext.embed.default:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/default.html.twig"
    ezsettings.default.ng_fieldtypes.ezrichtext.embed.default_inline:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/default_inline.html.twig"
    ezsettings.default.ng_fieldtypes.ezrichtext.embed.location:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/location.html.twig"
    ezsettings.default.ng_fieldtypes.ezrichtext.embed.location_denied:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/location_denied.html.twig"
    ezsettings.default.ng_fieldtypes.ezrichtext.embed.location_inline:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/location_inline.html.twig"
    ezsettings.default.ng_fieldtypes.ezrichtext.embed.location_inline_denied:
        template: "@@NetgenEzPlatformSiteApi/default/field_type/ezrichtext/embed/location_inline_denied.html.twig"

    # Default Site API settings under eZ Platform 'ezpublish/system' configuration node
    ezsettings.default.ng_fallback_to_secondary_content_view: false
    ezsettings.default.ng_fallback_without_subrequest: false
    ezsettings.default.ng_richtext_embed_without_subrequest: false
    ezsettings.default.ng_xmltext_embed_without_subrequest: false
    ezsettings.default.ng_cross_siteaccess_routing: true
    ezsettings.default.ng_cross_siteaccess_routing_prefer_translation_siteaccess: false
    ezsettings.default.ng_named_query: []
    ezsettings.default.ngcontent_view: []
    ezsettings.default.ngcontent_view_defaults:
        asset_image:
            default:
                template: '%netgen.ezplatform_site.default_view_templates.content.asset_image%'
                match: []
        embed:
            image:
                template: '%netgen.ezplatform_site.default_view_templates.content.embed_image%'
                match:
                    Identifier\ContentType: '%netgen.ezplatform_site.content_view.image_embed_content_type_identifiers%'
            default:
                template: "%netgen.ezplatform_site.default_view_templates.content.embed%"
                match: []
        embed-inline:
            default:
                template: "%netgen.ezplatform_site.default_view_templates.content.embed_inline%"
                match: []
        # Default full view is intentionally disabled because for some cases we depend on Content
        # redirecting to the homepage when the full view is not configured.
        #full:
        #    default:
        #        template: "%netgen.ezplatform_site.default_view_templates.content.full%"
        #        match: []
        line:
            default:
                template: "%netgen.ezplatform_site.default_view_templates.content.line%"
                match: []
        text_linked:
            default:
                template: "%netgen.ezplatform_site.default_view_templates.content.text_linked%"
                match: []
