name: Tests

on:
    push:
        branches:
            - 'master'
            - '[0-9].[0-9]+'
    pull_request: ~

jobs:
    tests:
        name: ${{ matrix.php }} ${{ matrix.coverage }} ${{ matrix.kernel }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    - php: '7.1'
                      phpunit: 'phpunit.xml'
                      coverage: 'unit'
                      kernel: '~7.4.4'
                    - php: '7.1'
                      phpunit: 'phpunit-integration-legacy.xml'
                      coverage: 'integration'
                      kernel: '~7.4.4'

                    - php: '7.1'
                      phpunit: 'phpunit.xml'
                      coverage: 'unit'
                      kernel: '~7.5.13'
                    - php: '7.1'
                      phpunit: 'phpunit-integration-legacy.xml'
                      coverage: 'integration'
                      kernel: '~7.5.13'

                    - php: '7.2'
                      phpunit: 'phpunit.xml'
                      coverage: 'unit'
                    - php: '7.2'
                      phpunit: 'phpunit-integration-legacy.xml'
                      coverage: 'integration'

                    - php: '7.3'
                      phpunit: 'phpunit.xml'
                      coverage: 'unit'
                    - php: '7.3'
                      phpunit: 'phpunit-integration-legacy.xml'
                      coverage: 'integration'

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug

            - run: composer require --no-update ezsystems/ezpublish-kernel="${{ matrix.kernel }}"
              if: matrix.kernel
            - run: composer --version
            - run: composer validate --strict
            - run: composer update --prefer-dist
            - run: vendor/bin/phpunit -c ${{ matrix.phpunit }} --colors=always --coverage-clover=coverage.xml
            - run: bash <(curl -s https://codecov.io/bash) -F ${{ matrix.coverage }}
